
# Configuration file for the imp_ror

# Some lines are optional and can be removed entirely
# e.g. data version and data date, if these are derived
# from the source file name or are in the CL arguments.
# See ReadMe for further details.

# If a line is present its entry must be a string enclosed 
# in double quotes (even if an empty string, "", 
# or an integer, e.g. "5433").

# This file normally located in the installation folder 
# i.e. above the bin folder with the .exe

[data]
data_version=""
data_date=""


[files]
data_folder_path="E:\\MDR source data\\ROR\\data"
log_folder_path="E:\\MDR source data\\ROR\\logs"
output_folder_path="E:\\MDR source data\\ROR\\outputs"
src_file_name="v1.59-2025-01-23-ror-data_schema_v2.json"


[database]
db_host="localhost"
db_user="postgres"
db_password="WinterIsComing!"
db_port="5433"
